###
# Copyright (2016-2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- hosts: localhost
  vars:
    config: "oneview_config.json"
  tasks:

#------------------ server profile template Nublar_ESXi
     - name: Get uri for network iSCSI-Deployment
       oneview_ethernet_network_facts:
         config:         "{{ config }}"
         name:           "iSCSI-Deployment"
     - set_fact:         var_iSCSI_Deployment="{{ethernet_networks[0].uri}}"
 
     - name: Get uri for network iSCSI-Deployment
       oneview_ethernet_network_facts:
         config:         "{{ config }}"
         name:           "iSCSI-Deployment"
     - set_fact:         var_iSCSI_Deployment="{{ethernet_networks[0].uri}}"
 
     - name: Get uri for network ib-mgmt
       oneview_ethernet_network_facts:
         config:         "{{ config }}"
         name:           "ib-mgmt"
     - set_fact:         var_ib_mgmt="{{ethernet_networks[0].uri}}"
 
     - name: Get uri for network ib-mgmt
       oneview_ethernet_network_facts:
         config:         "{{ config }}"
         name:           "ib-mgmt"
     - set_fact:         var_ib_mgmt="{{ethernet_networks[0].uri}}"
 
     - name: Get uri for network vSphereVMotion
       oneview_ethernet_network_facts:
         config:         "{{ config }}"
         name:           "vSphereVMotion"
     - set_fact:         var_vSphereVMotion="{{ethernet_networks[0].uri}}"
 
     - name: Get uri for network vSphereVMotion
       oneview_ethernet_network_facts:
         config:         "{{ config }}"
         name:           "vSphereVMotion"
     - set_fact:         var_vSphereVMotion="{{ethernet_networks[0].uri}}"
 
     - name: Get uri for network set_Prod
       oneview_network_set_facts:
         config:         "{{ config }}"
         name:           "set_Prod"
     - set_fact:         var_set_Prod="{{network_sets[0].uri}}"
 
     - name: Get uri for network set_Prod
       oneview_network_set_facts:
         config:         "{{ config }}"
         name:           "set_Prod"
     - set_fact:         var_set_Prod="{{network_sets[0].uri}}"
 
     - name: Get uri for network iSCSI-A
       oneview_ethernet_network_facts:
         config:         "{{ config }}"
         name:           "iSCSI-A"
     - set_fact:         var_iSCSI_A="{{ethernet_networks[0].uri}}"
 
     - name: Get uri for network iSCSI-B
       oneview_ethernet_network_facts:
         config:         "{{ config }}"
         name:           "iSCSI-B"
     - set_fact:         var_iSCSI_B="{{ethernet_networks[0].uri}}"
 
     - name: Get uri for network vSphereFT
       oneview_ethernet_network_facts:
         config:         "{{ config }}"
         name:           "vSphereFT"
     - set_fact:         var_vSphereFT="{{ethernet_networks[0].uri}}"
 
     - name: Get uri for network vSphereFT
       oneview_ethernet_network_facts:
         config:         "{{ config }}"
         name:           "vSphereFT"
     - set_fact:         var_vSphereFT="{{ethernet_networks[0].uri}}"
 
     - name: Create server profile template Nublar_ESXi
       oneview_server_profile_template:
         config: "{{ config }}"
         state: present
         data:
             name:                       "Nublar_ESXi"
             description:                "ESXi 6.7 Update 2 Build 13981272 mit NCM 6.1 und iSUT 2.4"
             serverProfileDescription:   "Nublar_ESXi"
             enclosureGroupName:         "Nublar_EG_3e"
             serverHardwareTypeName:     "SY 480 Gen10 1"
             affinity:                   "Bay"
             macType:                    "Virtual"
             wwnType:                    "Virtual"
             serialNumberType:           "Virtual"
             hideUnusedFlexNics:         true  
             iscsiInitiatorNameType:     "AutoGenerated"
             firmware:
                 manageFirmware:            true
                 forceInstallFirmware:      false
                 firmwareInstallType:       "FirmwareOnlyOfflineMode"
                 firmwareActivationType:    "Immediate"
                 firmwareBaselineName:      "HPE Synergy Custom SPP 201903 2019 08 25"
             osDeploymentSettings:
                 osDeploymentPlanName:      "nublarEsxiUpdated"
                 osCustomAttributes:
                     name:      "ManagementNIC.vlanid"
                     value:     
                     name:      "Hostname"
                     value:     
                     name:      "ManagementNIC.ipaddress"
                     value:     
                     name:      "ManagementNIC.netmask"
                     value:     
                     name:      "ManagementNIC2.mac"
                     value:     
                     name:      "ManagementNIC.mac"
                     value:     
                     name:      "ManagementNIC.constraint"
                     value:     auto
                     name:      "ManagementNIC.ipv4disable"
                     value:     False
                     name:      "ManagementNIC.networkuri"
                     value:     
                     name:      "ManagementNIC.dhcp"
                     value:     False
                     name:      "ManagementNIC.connectionid"
                     value:     
                     name:      "DomainName"
                     value:     ad.nublar.de
                     name:      "ManagementNIC.dns1"
                     value:     
                     name:      "Password"
                     value:     
                     name:      "ManagementNIC.gateway"
                     value:     
                     name:      "ManagementNIC.dns2"
                     value:     
                     name:      "ManagementNIC2.vlanid"
                     value:     
                     name:      "ManagementNIC2.constraint"
                     value:     auto
                     name:      "ManagementNIC2.ipv4disable"
                     value:     False
                     name:      "ManagementNIC2.networkuri"
                     value:     
                     name:      "ManagementNIC2.dhcp"
                     value:     False
                     name:      "ManagementNIC2.connectionid"
                     value:     
                     name:      "SSH"
                     value:     enabled
             bootMode:
                 manageMode:    true
                 mode:          "UEFIOptimized"
                 pxeBootPolicy: "Auto"
                 secureBoot:    "Unmanaged"
             boot:
                 manageBoot: true
                 order:
                     - "HardDisk" 
             bios:
                 manageBios:     true
                 overriddenSettings:
                     - id:    "CollabPowerControl" 
                       value: "Disabled" 
                     - id:    "PowerRegulator" 
                       value: "StaticHighPerf" 
                     - id:    "NumaGroupSizeOpt" 
                       value: "Clustered" 
                     - id:    "EnergyEfficientTurbo" 
                       value: "Disabled" 
                     - id:    "MinProcIdlePower" 
                       value: "NoCStates" 
                     - id:    "EnergyPerfBias" 
                       value: "MaxPerf" 
                     - id:    "WorkloadProfile" 
                       value: "Virtualization-MaxPerformance" 
                     - id:    "MinProcIdlePkgState" 
                       value: "NoState" 
                     - id:    "UncoreFreqScaling" 
                       value: "Maximum" 
                     - id:    "IntelUpiPowerManagement" 
                       value: "Disabled" 
                     - id:    "SubNumaClustering" 
                       value: "Enabled" 
                 controllers:
                     - deviceSlot: "Embedded"
                       mode: "Mixed"
                       initialize: true
                       logicalDrives:
                         - name: local-raid1
                           raidLevel: "RAID1"
                           bootable: "false"
                           numPhysicalDrives: 2
                           driveTechnology: 
                           sasLogicalJBODId: null
             connectionSettings:
                 connections:
                     - id: 1
                       portId: "Mezz 3:1-a"
                       name: "Deployment Network A"
                       functionType: "Ethernet"
                       networkUri: "{{var_iSCSI_Deployment}}"   # network name iSCSI-Deployment 
                       networkUri: "{{var_iSCSI_Deployment}}"   # network name iSCSI-Deployment 
                       requestedMbps: 2500
                       requestedVFs: Auto
                       ipv4:
                         ipAddressSource: "SubnetPool"
                       boot: 
                         priority: "Primary"
                         bootVlanId: null
                         ethernetBootType: "iSCSI"
                         bootVolumeSource: "UserDefined"
                         iscsi:
                             chapLevel: "None"
                             firstBootTargetIp: 
                             initiatorNameSource: "ProfileInitiatorName"
                             secondBootTargetIp: 
                             secondBootTargetPort: 
                     - id: 2
                       portId: "Mezz 3:2-a"
                       name: "Deployment Network B"
                       functionType: "Ethernet"
                       networkUri: "{{var_iSCSI_Deployment}}"   # network name iSCSI-Deployment 
                       networkUri: "{{var_iSCSI_Deployment}}"   # network name iSCSI-Deployment 
                       requestedMbps: 2500
                       requestedVFs: Auto
                       ipv4:
                         ipAddressSource: "SubnetPool"
                       boot: 
                         priority: "Secondary"
                         bootVlanId: null
                         ethernetBootType: "iSCSI"
                         bootVolumeSource: "UserDefined"
                         iscsi:
                             chapLevel: "None"
                             firstBootTargetIp: 
                             initiatorNameSource: "ProfileInitiatorName"
                             secondBootTargetIp: 
                             secondBootTargetPort: 
                     - id: 3
                       portId: "Mezz 3:1-d"
                       name: "mgmt-1"
                       functionType: "Ethernet"
                       networkUri: "{{var_ib_mgmt}}"   # network name ib-mgmt 
                       networkUri: "{{var_ib_mgmt}}"   # network name ib-mgmt 
                       requestedMbps: 2500
                       requestedVFs: 0
                       boot: 
                         priority: "NotBootable"
                     - id: 4
                       portId: "Mezz 3:2-d"
                       name: "mgmt-2"
                       functionType: "Ethernet"
                       networkUri: "{{var_ib_mgmt}}"   # network name ib-mgmt 
                       networkUri: "{{var_ib_mgmt}}"   # network name ib-mgmt 
                       requestedMbps: 2500
                       requestedVFs: 0
                       boot: 
                         priority: "NotBootable"
                     - id: 5
                       portId: "Mezz 3:1-e"
                       name: "vmotion-1"
                       functionType: "Ethernet"
                       networkUri: "{{var_vSphereVMotion}}"   # network name vSphereVMotion 
                       networkUri: "{{var_vSphereVMotion}}"   # network name vSphereVMotion 
                       requestedMbps: 2500
                       requestedVFs: 0
                       boot: 
                         priority: "NotBootable"
                     - id: 6
                       portId: "Mezz 3:2-e"
                       name: "vmotion-2"
                       functionType: "Ethernet"
                       networkUri: "{{var_vSphereVMotion}}"   # network name vSphereVMotion 
                       networkUri: "{{var_vSphereVMotion}}"   # network name vSphereVMotion 
                       requestedMbps: 2500
                       requestedVFs: 0
                       boot: 
                         priority: "NotBootable"
                     - id: 9
                       portId: "Mezz 3:1-b"
                       name: "prod-1"
                       functionType: "Ethernet"
                       networkUri: "{{var_set_Prod}}"   # network name set_Prod 
                       networkUri: "{{var_set_Prod}}"   # network name set_Prod 
                       requestedMbps: 2500
                       requestedVFs: 0
                       boot: 
                         priority: "NotBootable"
                     - id: 10
                       portId: "Mezz 3:2-b"
                       name: "prod-2"
                       functionType: "Ethernet"
                       networkUri: "{{var_set_Prod}}"   # network name set_Prod 
                       networkUri: "{{var_set_Prod}}"   # network name set_Prod 
                       requestedMbps: 2500
                       requestedVFs: 0
                       boot: 
                         priority: "NotBootable"
                     - id: 11
                       portId: "Mezz 3:1-c"
                       name: "iSCSI-A"
                       functionType: "Ethernet"
                       networkUri: "{{var_iSCSI_A}}"   # network name iSCSI-A 
                       requestedMbps: 2500
                       requestedVFs: 0
                       boot: 
                         priority: "NotBootable"
                     - id: 12
                       portId: "Mezz 3:2-c"
                       name: "iSCSI-B"
                       functionType: "Ethernet"
                       networkUri: "{{var_iSCSI_B}}"   # network name iSCSI-B 
                       requestedMbps: 2500
                       requestedVFs: 0
                       boot: 
                         priority: "NotBootable"
                     - id: 13
                       portId: "Mezz 3:1-f"
                       name: "ft-1"
                       functionType: "Ethernet"
                       networkUri: "{{var_vSphereFT}}"   # network name vSphereFT 
                       networkUri: "{{var_vSphereFT}}"   # network name vSphereFT 
                       requestedMbps: 2500
                       requestedVFs: 0
                       boot: 
                         priority: "NotBootable"
                     - id: 14
                       portId: "Mezz 3:2-f"
                       name: "ft-2"
                       functionType: "Ethernet"
                       networkUri: "{{var_vSphereFT}}"   # network name vSphereFT 
                       networkUri: "{{var_vSphereFT}}"   # network name vSphereFT 
                       requestedMbps: 2500
                       requestedVFs: 0
                       boot: 
                         priority: "NotBootable"
       delegate_to: localhost
 
