---
- hosts: localhost
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Ensure that a firmware bundle is present
      oneview_firmware_bundle:
        config: "{{ config }}"
        state: present
        file_path: "{{ playbook_dir }}/files/HPE_Synergy_Custom_SPP_2019.03.20190825_Z7550-96751.iso"
      delegate_to: localhost
    - debug: var=firmware_bundle
