---
- hosts: all
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"
    server_profile_name: Server profile with OS Deployment Plan
    artifact_bundle_filepath: '{{ playbook_dir }}/files/HPE-ESXi-6.7-2019-07-24-v4.2.zip"
  tasks:
    - name: Ensure the Artifact Bundle is present
      image_streamer_artifact_bundle:
        config: '{{ config }}'
        state: present
        data:
          localArtifactBundleFilePath: '{{ artifact_bundle_filepath }}'
      delegate_to: localhost

    - name: 'Validate the Artifact Bundle'
      fail: msg="An Artifact Bundle with at least one Deployment Plan is required to run this example."
      when: (artifact_bundle.deploymentPlans.0 is undefined or artifact_bundle.deploymentPlans.0 is none)

    - name: Extract the Artifact Bundle
      image_streamer_artifact_bundle:
        config: "{{ config }}"
        state: extracted
        data:
          name: '{{ artifact_bundle.name }}'
      delegate_to: localhost
