---
- hosts: localhost
  vars:
    config: "{{ playbook_dir }}/A_oneview_config.json"
  tasks:
  - name: Login to API and retrieve AUTH-Token
    uri:
      validate_certs: yes
      headers:
        X-Api-Version: "1000"
        Content-Type: application/json
      url: https://a-dcb-syn0001.ad.nublar.de/rest/login-sessions
      method: POST
      body_format: json
      body:
        authLoginDomain: "LOCAL"
        password: "Concat123"
        userName: "Administrator"
        loginMsgAck: "true"
    register: var_this

  - set_fact: var_token='{{ var_this["json"]["sessionID"] }}'

  - name: get Hypervisor manager uri
    uri:
      validate_certs: yes
      headers:
        Auth: "{{ var_token }}"
        X-Api-Version: "1000"
        Content-Type: application/json
      url: https://a-dcb-syn0001.ad.nublar.de/rest/hypervisor-managers
      method: GET
      body_format: json
      body:
      status_code: 200
    register: var_hypervisor_managers
  - set_fact: var_hypervisor_manager_uri="{{var_hypervisor_managers["json"]["members"][0]["uri"]}}"

  - name: Retrieve HVCP as name:uri dict
    uri:
      validate_certs: yes
      headers:
        Auth: "{{ var_token }}"
        X-Api-Version: "1000"
        Content-Type: application/json
      url: 'https://a-dcb-syn0001.ad.nublar.de/rest/hypervisor-cluster-profiles'
      method: GET
      status_code: 200
    register: var_hvcp
  - set_fact: hvcp={{[]}}
  - set_fact: hvcp="{{ hvcp +[{"name":item['name'], "uri":item['uri']}] }}"
    loop: "{{ var_hvcp.json.members | flatten }}"
  - debug: var=hvcp

    
  - name: Retrieve Volumes for HVCP
    oneview_volume_facts:
      config: "{{ config }}"

  - set_fact: hvcp_volumes={{[]}}
  - set_fact: hvcp_volumes="{{ hvcp_volumes + [item['name'],item['uri']]}} "
    when: item['name'] is search("A-PROD-") #CODE über alle Cluster loopen
    loop:
      "{{ storage_volumes | flatten }}"


  - name: Attach Volumes to Cluster
    uri:
      validate_certs: yes
      headers:
        Auth: "{{ var_token }}"
        X-Api-Version: "1000"
        Content-Type: application/json
      url: 'https://a-dcb-syn0001.ad.nublar.de{{ hvcp['uri'] }}'
      method: PUT
      body_format: json
      body:
        type: 'HypervisorClusterProfileV3'
        name: "{{ hvcp_name }}"
        hypervisorType: 'Vmware'
        sharedStorageVolumes:                       #CODE Anfang
        - storageVolumeUri: "{{ item['uri'] }}"
          hypervisorClusterVolume:
            action: ADD
            name: "{{ item['name'] }}"
          volumeFileSystemType: VMFS                #CODE Ende
      status_code: 202
    with_items: storage_volumes
    register: var_return

