---
- hosts: all
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"
    server_profile_template_name: "Nublar_ESXi"
    server_profile_template_description: "ESXi 6.7 Update 2 Build 13981272 mit NCM 6.1 und iSUT 2.4"
    server_hardware_type_name: "SY 480 Gen10 1"
    enclosure_group_name: "Nublar_EG_3e" #CODE
    server_hardware_type_uri: "/rest/server-hardware-types/5DC5ABD6-5F43-4D76-BB35-04DD814369D0"
    management_network_dns1: "10.40.72.10" #CODE
    management_network_dns2: "10.40.72.11" #CODE
    management_network_netmask: "255.25.254.0" #CODE
    management_network_gateway: "10.40.211.254" #CODE
    deployment_plan_name: "nublarESXiUpdated" #CODE

  tasks:
    - name: Find Deployment Plan URI
      oneview_os_deployment_plan_facts:
        config: "{{ config }}"
        name: "{{ deployment_plan_name }}"
    - set_fact: deployment_plan_uri="{{ os_deployment_plans[0].uri }}"

    - name: Find Firmware Baseline URI
      oneview_firmware_driver_facts:
        config: "{{ config }}"
    - set_fact: firmware_baseline_uri="{{ firmware_drivers[0].uri }}"

    - name: Find Network Set URI
      oneview_network_set_facts:
        config: "{{ config }}"

    - set_fact: prod_netset_uri="{{ item.uri }}"
      no_log: True
      loop: "{{ network_sets }}"
      when: item.name is match "set_Prod"

    - name: Gather network URIs
      oneview_ethernet_network_facts:
        config: "{{ config }}"

    - set_fact: deploy_network_uri="{{ item.uri }}"
      no_log: True
      loop: "{{ ethernet_networks }}"
      when: item.name is match "iSCSI-Deployment"

    - set_fact: management_network_uri="{{ item.uri }}"
      no_log: True
      loop: "{{ ethernet_networks }}"
      when: item.name is match "ib-mgmt"

    - set_fact: vmotion_network_uri="{{ item.uri }}"
      no_log: True
      loop: "{{ ethernet_networks }}"
      when: item.name is match "vSphereVMotion"

    - set_fact: iscsi_a_network_uri="{{ item.uri }}"
      no_log: True
      loop: "{{ ethernet_networks }}"
      when: item.name is match "iSCSI-A"

    - set_fact: iscsi_b_network_uri="{{ item.uri }}"
      no_log: True
      loop: "{{ ethernet_networks }}"
      when: item.name is match "iSCSI-B"

    - set_fact: ft_network_uri="{{ item.uri }}"
      no_log: True
      loop: "{{ ethernet_networks }}"
      when: item.name is match "vSphereFT"

    - name: Create Server Profile Template
      oneview_server_profile_template:
        config: "{{ config }}"
        state: present
        data:
          type: ServerProfileTemplateV6
          name: "{{ server_profile_template_name }}"
          description: "{{ server_profile_template_description }}"
          serverProfileDescription: ''
          serverHardwareTypeName: "{{ server_hardware_type_name }}"
          enclosureGroupName: "{{ enclosure_group_name }}"
          affinity: Bay
          hideUnusedFlexNics: true
          macType: Virtual
          wwnType: Virtual
          serialNumberType: Virtual
          iscsiInitiatorNameType: AutoGenerated
          osDeploymentSettings:
            osDeploymentPlanUri: "{{ deployment_plan_uri }}"
            osCustomAttributes:
            - name: DomainName
              value: ad.nublar.de
              constraints: '{"helpText":""}'
              type: fqdn
            - name: Hostname
              value: ''
              constraints: '{"helpText":""}'
              type: hostname
            - name: ManagementNIC.connectionid
              value: '3'
            - name: ManagementNIC.dns1
              value: 10.40.72.10
            - name: ManagementNIC.dns2
              value: 10.40.72.11
            - name: ManagementNIC.gateway
              value: 10.40.195.254
            - name: ManagementNIC.ipaddress
              value: ''
            - name: ManagementNIC.netmask
              value: 255.255.254.0
            - name: ManagementNIC.networkuri
              value: "{{ management_network_uri }}"
            - name: ManagementNIC.constraint
              value: userspecified
            - name: ManagementNIC.vlanid
              value: '0'
            - name: ManagementNIC2.connectionid
              value: '4'
            - name: ManagementNIC2.networkuri
              value: "{{ management_network_uri }}"
            - name: ManagementNIC2.constraint
              value: userspecified
            - name: ManagementNIC2.vlanid
              value: '0'
            - name: Password
              value: ''
            - name: SSH
              value: enabled
              constraints: '{"options":["enabled","disabled"]}'
              type: option
            complianceControl: Checked
          firmware:
            manageFirmware: true
            firmwareBaselineUri: "{{ firmware_baseline_uri }}"
            forceInstallFirmware: false
            firmwareInstallType: FirmwareOnlyOfflineMode
            firmwareActivationType: Immediate
            complianceControl: Checked
          connectionSettings:
            connections:
            - id: 1
              name: Deployment Network A
              functionType: Ethernet
              portId: Mezz 3:1-a
              requestedMbps: '2500'
              networkUri: "{{ deploy_network_uri }}"
              lagName: 
              isolatedTrunk: false
              requestedVFs: Auto
              ipv4:
                ipAddressSource: SubnetPool
              boot:
                priority: Primary
                bootVlanId: 
                ethernetBootType: iSCSI
                bootVolumeSource: UserDefined
                iscsi:
                  initiatorNameSource: ProfileInitiatorName
                  secondBootTargetIp: ''
                  chapLevel: None
            - id: 2
              name: Deployment Network B
              functionType: Ethernet
              portId: Mezz 3:2-a
              requestedMbps: '2500'
              networkUri: "{{ deploy_network_uri }}"
              lagName: 
              isolatedTrunk: false
              requestedVFs: Auto
              ipv4:
                ipAddressSource: SubnetPool
              boot:
                priority: Secondary
                bootVlanId: 
                ethernetBootType: iSCSI
                bootVolumeSource: UserDefined
                iscsi:
                  initiatorNameSource: ProfileInitiatorName
                  secondBootTargetIp: ''
                  chapLevel: None
            - id: 3
              name: mgmt-1
              functionType: Ethernet
              portId: Mezz 3:1-d
              requestedMbps: '2500'
              networkUri: "{{ management_network_uri }}"
              lagName: 
              isolatedTrunk: false
              requestedVFs: '0'
              ipv4: {}
              boot:
                priority: NotBootable
                iscsi: {}
            - id: 4
              name: mgmt-2
              functionType: Ethernet
              portId: Mezz 3:2-d
              requestedMbps: '2500'
              networkUri: "{{ management_network_uri }}"
              lagName: 
              isolatedTrunk: false
              requestedVFs: '0'
              ipv4: {}
              boot:
                priority: NotBootable
                iscsi: {}
            - id: 5
              name: vmotion-1
              functionType: Ethernet
              portId: Auto
              requestedMbps: '2500'
              networkUri: "{{ vmotion_network_uri }}"
              lagName: 
              isolatedTrunk: false
              requestedVFs: '0'
              ipv4: {}
              boot:
                priority: NotBootable
                iscsi: {}
            - id: 6
              name: vmotion-2
              functionType: Ethernet
              portId: Auto
              requestedMbps: '2500'
              networkUri: "{{ vmotion_network_uri }}"
              lagName: 
              isolatedTrunk: false
              requestedVFs: '0'
              ipv4: {}
              boot:
                priority: NotBootable
                iscsi: {}
            - id: 7
              name: prod-1
              functionType: Ethernet
              portId: Auto
              requestedMbps: '2500'
              networkUri: "{{ prod_netset_uri }}"
              lagName: 
              isolatedTrunk: false
              requestedVFs: '0'
              ipv4: {}
              boot:
                priority: NotBootable
                iscsi: {}
            - id: 8
              name: prod-2
              functionType: Ethernet
              portId: Auto
              requestedMbps: '2500'
              networkUri: "{{ prod_netset_uri }}"
              lagName: 
              isolatedTrunk: false
              requestedVFs: '0'
              ipv4: {}
              boot:
                priority: NotBootable
                iscsi: {}
            - id: 9
              name: iSCSI-A
              functionType: Ethernet
              portId: Auto
              requestedMbps: '2500'
              networkUri: "{{ iscsi_a_network_uri }}"
              lagName: 
              isolatedTrunk: false
              requestedVFs: '0'
              ipv4: {}
              boot:
                priority: NotBootable
                iscsi: {}
            - id: 10
              name: iSCSI-B
              functionType: Ethernet
              portId: Auto
              requestedMbps: '2500'
              networkUri: "{{ iscsi_b_network_uri }}"
              lagName: 
              isolatedTrunk: false
              requestedVFs: '0'
              ipv4: {}
              boot:
                priority: NotBootable
                iscsi: {}
            - id: 11
              name: ft-1
              functionType: Ethernet
              portId: Auto
              requestedMbps: '2500'
              networkUri: "{{ ft_network_uri }}"
              lagName: 
              isolatedTrunk: false
              requestedVFs: '0'
              ipv4: {}
              boot:
                priority: NotBootable
                iscsi: {}
            - id: 12
              name: ft-2
              functionType: Ethernet
              portId: Auto
              requestedMbps: '2500'
              networkUri: "{{ ft_network_uri }}"
              lagName: 
              isolatedTrunk: false
              requestedVFs: '0'
              ipv4: {}
              boot:
                priority: NotBootable
                iscsi: {}
            manageConnections: true
            complianceControl: Checked
          bootMode:
            manageMode: true
            mode: UEFIOptimized
            secureBoot: Unmanaged
            pxeBootPolicy: Auto
            complianceControl: Checked
          boot:
            manageBoot: true
            order:
            - HardDisk
            complianceControl: Checked
          bios:
            manageBios: true
            overriddenSettings:
            - id: IntelUpiPowerManagement
              value: Disabled
            - id: UncoreFreqScaling
              value: Maximum
            - id: EnergyEfficientTurbo
              value: Disabled
            - id: MinProcIdlePkgState
              value: NoState
            - id: PowerRegulator
              value: StaticHighPerf
            - id: MinProcIdlePower
              value: NoCStates
            - id: SubNumaClustering
              value: Enabled
            - id: EnergyPerfBias
              value: MaxPerf
            - id: CollabPowerControl
              value: Disabled
            - id: WorkloadProfile
              value: Virtualization-MaxPerformance
            - id: NumaGroupSizeOpt
              value: Clustered
            complianceControl: Checked
          managementProcessor:
            manageMp: false
            mpSettings: []
            complianceControl: Unchecked
          localStorage:
            sasLogicalJBODs: []
            controllers:
            - logicalDrives:
              - name: local-raid1
                raidLevel: RAID1
                bootable: false
                numPhysicalDrives: 2
                driveTechnology: 
                sasLogicalJBODId: 
                accelerator: Unmanaged
              deviceSlot: Embedded
              mode: Mixed
              initialize: false
              driveWriteCache: Unmanaged
            complianceControl: Unchecked
          sanStorage:
            manageSanStorage: true
            hostOSType: VMware (ESXi)
            volumeAttachments: []
            sanSystemCredentials: []
            complianceControl: CheckedMinimum
          
          


    - debug: var=server_profile_template

