---
- hosts: localhost
  vars:
    config: "{{ playbook_dir }}/A_oneview_config.json"
    hvcp_name: A-TST
  tasks:
  - name: Login to API and retrieve AUTH-Token
    uri:
      validate_certs: yes
      headers:
        X-Api-Version: "1000"
        Content-Type: application/json
      url: https://a-dcb-syn0001.ad.nublar.de/rest/login-sessions
      method: POST
      body_format: json
      body:
        authLoginDomain: "LOCAL"
        password: "Concat123"
        userName: "Administrator"
        loginMsgAck: "true"
    register: var_this

  - set_fact: var_token='{{ var_this["json"]["sessionID"] }}'

  - name: get switch layou
    uri:
      validate_certs: yes
      headers:
        Auth: "{{ var_token }}"
        X-Api-Version: "1000"
        Content-Type: application/json
      url: https://a-dcb-syn0001.ad.nublar.de/rest/hypervisor-cluster-profiles/virtualswitch-layout
      method: POST
      body_format: json
      body:
        {
                                "serverProfileTemplateUri" : "/rest/server-profile-templates/7e5a9d5e-ce02-4337-b562-2c7bc67a8773",
                                "hypervisorClusterSettings" :
                                {
                                    "multiNicVMotion" : false,
                                    "virtualSwitchType" : "Distributed",
                                    "distributedSwitchUsage" : "GeneralNetworks",
                                    "type" : "Vmware"
                                }
                            }
      status_code: 200
    register: result

  - debug: var=result
