###
# Copyright (2016-2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- hosts: all
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"
    ethernet_networks:
      - ei-1300-48 #CODE network.namen aus Spalte B
      - prod-1000-0
      - prt-1100-16
      - tst-1200-32
  tasks:
    - debug: var=ethernet_networks
    - name: Create a Network Set
      oneview_network_set:
        config: '{{ config }}'
        state: present
        data:
          type: "network-setV4"
          name: 'set_Prod' #CODE Synergy-Networks Spalte L
          networkUris: "{{ ethernet_networks }}"
      delegate_to: localhost

