---
- hosts: all
  vars:
    config: '{{ playbook_dir }}/oneview_config.json'
    storage_system_name: a-dcb-sto0100.ad.nublar.de #CODE für beide Seiten
    storage_volume_template_name: ESX_Data_Volume_on_Nimble #CODE Synergy-Nimble Zeile 13
    volume_name: TestVol #CODE {{Zone}}-{{Cluster}}-000[12] <- Cluster aus Synergy-VMware Spalte D, zwei Volumes pro Cluster
  tasks:
    - name: Find Storage Volume Template by name
      oneview_storage_volume_template_facts:
        config: "{{ config }}"
        name: "{{ storage_volume_template_name }}"

    - set_fact: storage_volume_template_uri="{{ storage_volume_templates.0.uri }}"
    - set_fact: storage_pool_uri="{{ storage_volume_templates.0.storagePoolUri }}"
    - set_fact: performance_policy="{{ storage_volume_templates.0.properties.performancePolicy.default }}"

    - name: Create a Volume based on a Storage Volume Template
      oneview_volume:
        config: '{{ config }}'
        state: present
        data:
          properties:
            name: "{{ volume_name }}"
            description: ''
            storagePool: "{{ storage_pool_uri }}"
            size: 8796093022208
            provisioningType: Thin
            isShareable: true
            templateVersion: '1.0'
            isDeduplicated: true
            performancePolicy: "{{ performance_policy }}"
            folder:
            volumeSet:
            isEncrypted: false
            isPinned: false
            iopsLimit:
            dataTransferLimit:
          templateUri: "{{ storage_volume_template_uri }}"
          isPermanent: true
          initialScopeUris: 



